USE WebShopDB
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0555,'Scanning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0783,'Facility');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0800,'Høje Taastrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0877,'København C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0892,'Sjælland USF P');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0893,'Sjælland USF B');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0894,'Udbetaling');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0899,'Kommuneservice');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0900,'København C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0910,'København C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0913,'Københavns Pakkecenter');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0914,'Københavns Pakkecenter');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0917,'Københavns Pakkecenter');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0918,'Københavns Pakke BRC');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0919,'Returprint BRC');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0929,'København C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0960,'Internationalt Postcenter');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (0999,'København C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1001,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1002,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1003,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1004,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1005,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1006,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1007,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1008,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1009,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1010,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1011,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1012,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1013,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1014,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1015,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1016,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1017,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1018,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1019,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1020,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1021,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1022,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1023,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1024,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1025,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1026,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1045,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1050,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1051,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1052,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1053,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1054,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1055,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1055,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1056,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1057,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1058,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1059,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1060,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1061,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1062,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1063,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1064,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1065,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1066,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1067,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1068,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1069,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1070,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1071,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1072,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1073,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1074,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1092,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1093,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1095,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1098,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1100,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1101,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1102,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1103,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1104,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1105,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1106,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1107,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1110,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1111,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1112,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1113,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1114,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1115,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1116,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1117,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1118,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1119,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1120,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1121,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1122,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1123,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1124,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1125,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1126,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1127,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1128,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1129,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1130,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1131,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1140,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1147,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1148,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1150,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1151,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1152,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1153,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1154,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1155,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1156,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1157,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1158,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1159,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1160,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1161,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1162,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1164,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1165,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1165,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1166,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1167,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1168,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1169,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1170,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1171,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1172,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1173,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1174,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1175,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1200,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1201,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1202,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1203,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1204,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1205,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1206,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1207,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1208,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1209,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1210,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1211,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1212,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1213,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1214,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1215,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1216,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1217,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1218,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1219,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1220,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1221,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1240,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1250,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1251,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1252,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1253,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1254,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1255,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1256,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1257,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1259,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1259,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1260,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1261,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1263,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1263,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1264,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1265,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1266,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1267,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1268,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1270,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1271,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1300,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1301,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1302,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1303,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1304,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1306,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1307,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1307,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1308,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1309,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1310,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1311,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1312,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1313,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1314,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1315,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1316,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1317,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1318,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1319,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1320,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1321,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1322,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1323,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1324,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1325,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1326,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1327,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1328,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1329,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1350,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1352,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1353,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1354,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1355,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1356,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1357,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1358,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1359,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1359,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1360,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1361,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1361,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1362,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1363,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1364,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1365,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1366,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1367,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1368,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1369,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1370,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1371,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1400,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1400,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1401,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1402,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1402,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1402,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1402,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1402,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1403,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1406,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1407,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1408,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1409,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1410,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1411,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1411,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1412,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1413,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1414,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1415,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1416,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1417,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1418,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1419,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1420,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1421,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1422,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1423,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1424,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1425,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1426,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1427,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1428,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1429,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1430,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1432,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1432,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1432,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1433,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1434,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1434,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1435,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1436,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1437,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1438,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1438,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1438,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1438,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1438,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1439,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1440,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1441,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1441,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1441,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1448,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1450,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1451,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1452,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1453,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1454,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1455,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1456,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1457,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1458,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1459,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1460,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1461,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1462,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1463,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1464,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1465,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1466,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1467,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1468,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1470,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1471,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1472,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1473,'København K');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1500,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1501,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1502,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1503,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1504,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1505,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1506,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1507,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1508,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1509,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1510,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1512,'Returpost');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1513,'Flytninger og Nejtak');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1532,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1533,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1550,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1550,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1551,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1552,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1553,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1553,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1554,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1555,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1556,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1557,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1558,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1559,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1560,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1561,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1561,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1562,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1563,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1564,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1567,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1568,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1569,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1570,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1570,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1571,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1572,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1573,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1574,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1575,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1576,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1577,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1577,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1577,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1592,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1599,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1600,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1601,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1602,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1603,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1604,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1605,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1606,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1607,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1608,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1609,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1610,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1611,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1612,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1613,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1614,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1615,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1616,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1617,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1618,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1619,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1620,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1620,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1621,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1622,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1623,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1624,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1630,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1631,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1632,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1633,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1634,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1635,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1650,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1651,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1652,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1653,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1654,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1655,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1656,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1657,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1658,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1659,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1660,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1660,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1661,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1662,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1663,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1664,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1665,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1666,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1667,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1668,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1669,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1670,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1671,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1671,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1672,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1673,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1674,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1675,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1676,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1677,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1699,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1700,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1701,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1702,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1703,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1704,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1705,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1706,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1707,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1708,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1709,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1710,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1711,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1711,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1712,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1714,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1715,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1716,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1717,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1718,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1719,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1720,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1721,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1722,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1723,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1724,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1725,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1726,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1727,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1728,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1729,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1730,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1731,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1732,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1733,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1734,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1735,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1736,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1737,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1738,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1739,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1749,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1750,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1751,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1752,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1753,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1754,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1755,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1756,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1757,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1758,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1759,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1760,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1761,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1762,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1763,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1764,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1765,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1766,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1770,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1771,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1772,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1773,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1774,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1775,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1777,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1780,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1782,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1785,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1786,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1787,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1790,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1799,'København V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1800,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1801,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1802,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1803,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1804,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1805,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1806,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1807,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1808,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1809,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1810,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1811,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1812,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1813,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1814,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1815,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1816,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1817,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1818,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1819,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1820,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1822,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1823,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1824,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1825,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1826,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1827,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1828,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1829,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1835,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1850,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1851,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1852,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1853,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1854,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1855,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1856,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1857,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1860,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1861,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1862,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1863,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1864,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1865,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1866,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1867,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1868,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1870,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1871,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1872,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1873,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1874,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1875,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1876,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1877,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1878,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1879,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1900,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1901,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1902,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1903,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1904,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1905,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1906,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1908,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1909,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1910,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1911,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1912,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1913,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1914,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1915,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1916,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1917,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1920,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1921,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1922,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1923,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1924,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1925,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1926,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1927,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1928,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1931,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1950,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1951,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1952,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1953,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1954,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1955,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1956,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1957,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1958,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1959,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1960,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1961,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1962,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1963,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1964,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1965,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1966,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1967,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1970,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1971,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1972,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1973,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (1974,'Frederiksberg C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2000,'Frederiksberg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2100,'København Ø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2150,'Nordhavn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2200,'København N');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2300,'København S');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2400,'København NV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2412,'Grønland');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2450,'København SV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2500,'Valby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2600,'Glostrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2605,'Brøndby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2610,'Rødovre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2620,'Albertslund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2625,'Vallensbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2630,'Taastrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2635,'Ishøj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2640,'Hedehusene');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2650,'Hvidovre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2660,'Brøndby Strand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2665,'Vallensbæk Strand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2670,'Greve');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2680,'Solrød Strand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2690,'Karlslunde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2700,'Brønshøj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2720,'Vanløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2730,'Herlev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2740,'Skovlunde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2750,'Ballerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2760,'Måløv');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2765,'Smørum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2770,'Kastrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2791,'Dragør');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2800,'Kongens Lyngby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2820,'Gentofte');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2830,'Virum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2840,'Holte');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2850,'Nærum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2860,'Søborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2870,'Dyssegård');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2880,'Bagsværd');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2900,'Hellerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2920,'Charlottenlund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2930,'Klampenborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2942,'Skodsborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2950,'Vedbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2960,'Rungsted Kyst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2970,'Hørsholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2980,'Kokkedal');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2990,'Nivå');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3000,'Helsingør');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3050,'Humlebæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3060,'Espergærde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3070,'Snekkersten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3080,'Tikøb');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3100,'Hornbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3120,'Dronningmølle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3140,'Ålsgårde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3150,'Hellebæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3200,'Helsinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3210,'Vejby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3220,'Tisvildeleje');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3230,'Græsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3250,'Gilleleje');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3300,'Frederiksværk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3310,'Ølsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3320,'Skævinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3330,'Gørløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3360,'Liseleje');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3370,'Melby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3390,'Hundested');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3400,'Hillerød');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3450,'Allerød');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3460,'Birkerød');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3480,'Fredensborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3490,'Kvistgård');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3500,'Værløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3520,'Farum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3540,'Lynge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3550,'Slangerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3600,'Frederikssund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3630,'Jægerspris');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3650,'Ølstykke');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3660,'Stenløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3670,'Veksø Sjælland');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3700,'Rønne');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3720,'Aakirkeby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3730,'Nexø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3740,'Svaneke');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3751,'Østermarie');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3760,'Gudhjem');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3770,'Allinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3782,'Klemensker');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3790,'Hasle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4000,'Roskilde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4030,'Tune');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4040,'Jyllinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4050,'Skibby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4060,'Kirke Såby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4070,'Kirke Hyllinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4100,'Ringsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4129,'Ringsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4130,'Viby Sjælland');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4140,'Borup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4160,'Herlufmagle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4171,'Glumsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4173,'Fjenneslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4174,'Jystrup Midtsj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4180,'Sorø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4190,'Munke Bjergby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4200,'Slagelse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4220,'Korsør');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4230,'Skælskør');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4241,'Vemmelev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4242,'Boeslunde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4243,'Rude');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4244,'Agersø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4245,'Omø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4250,'Fuglebjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4261,'Dalmose');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4262,'Sandved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4270,'Høng');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4281,'Gørlev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4291,'Ruds Vedby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4293,'Dianalund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4295,'Stenlille');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4296,'Nyrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4300,'Holbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4305,'Orø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4320,'Lejre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4330,'Hvalsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4340,'Tølløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4350,'Ugerløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4360,'Kirke Eskilstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4370,'Store Merløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4390,'Vipperød');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4400,'Kalundborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4420,'Regstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4440,'Mørkøv');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4450,'Jyderup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4460,'Snertinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4470,'Svebølle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4480,'Store Fuglede');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4490,'Jerslev Sjælland');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4500,'Nykøbing Sj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4520,'Svinninge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4532,'Gislinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4534,'Hørve');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4540,'Fårevejle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4550,'Asnæs');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4560,'Vig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4571,'Grevinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4572,'Nørre Asmindrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4573,'Højby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4581,'Rørvig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4583,'Sjællands Odde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4591,'Føllenslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4592,'Sejerø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4593,'Eskebjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4600,'Køge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4621,'Gadstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4622,'Havdrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4623,'Lille Skensved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4632,'Bjæverskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4640,'Faxe');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4652,'Hårlev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4653,'Karise');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4654,'Faxe Ladeplads');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4660,'Store Heddinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4671,'Strøby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4672,'Klippinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4673,'Rødvig Stevns');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4681,'Herfølge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4682,'Tureby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4683,'Rønnede');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4684,'Holmegaard');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4690,'Haslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4700,'Næstved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4720,'Præstø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4733,'Tappernøje');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4735,'Mern');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4736,'Karrebæksminde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4750,'Lundby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4760,'Vordingborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4771,'Kalvehave');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4772,'Langebæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4773,'Stensved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4780,'Stege');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4791,'Borre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4792,'Askeby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4793,'Bogø By');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4800,'Nykøbing F');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4840,'Nørre Alslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4850,'Stubbekøbing');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4862,'Guldborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4863,'Eskilstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4871,'Horbelev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4872,'Idestrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4873,'Væggerløse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4874,'Gedser');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4880,'Nysted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4891,'Toreby L');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4892,'Kettinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4894,'Øster Ulslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4895,'Errindlev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4900,'Nakskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4912,'Harpelunde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4913,'Horslunde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4920,'Søllested');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4930,'Maribo');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4941,'Bandholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4942,'Askø og Lilleø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4943,'Torrig L');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4944,'Fejø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4945,'Femø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4951,'Nørreballe');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4952,'Stokkemarke');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4953,'Vesterborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4960,'Holeby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4970,'Rødby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4983,'Dannemare');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4990,'Sakskøbing');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (4992,'Midtsjælland USF P');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5000,'Odense C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5029,'Odense C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5100,'Odense C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5200,'Odense V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5210,'Odense NV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5220,'Odense SØ');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5230,'Odense M');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5240,'Odense NØ');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5250,'Odense SV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5260,'Odense S');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5270,'Odense N');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5290,'Marslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5300,'Kerteminde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5320,'Agedrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5330,'Munkebo');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5350,'Rynkeby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5370,'Mesinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5380,'Dalby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5390,'Martofte');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5400,'Bogense');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5450,'Otterup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5462,'Morud');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5463,'Harndrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5464,'Brenderup Fyn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5466,'Asperup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5471,'Søndersø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5474,'Veflinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5485,'Skamby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5491,'Blommenslyst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5492,'Vissenbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5500,'Middelfart');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5540,'Ullerslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5550,'Langeskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5560,'Aarup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5580,'Nørre Aaby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5591,'Gelsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5592,'Ejby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5600,'Faaborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5601,'Lyø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5602,'Avernakø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5603,'Bjørnø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5610,'Assens');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5620,'Glamsbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5631,'Ebberup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5642,'Millinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5672,'Broby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5683,'Haarby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5690,'Tommerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5700,'Svendborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5750,'Ringe');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5762,'Vester Skerninge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5771,'Stenstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5772,'Kværndrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5792,'Årslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5800,'Nyborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5853,'Ørbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5854,'Gislev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5856,'Ryslinge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5863,'Ferritslev Fyn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5871,'Frørup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5874,'Hesselager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5881,'Skårup Fyn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5882,'Vejstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5883,'Oure');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5884,'Gudme');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5892,'Gudbjerg Sydfyn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5900,'Rudkøbing');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5932,'Humble');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5935,'Bagenkop');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5943,'Strynø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5953,'Tranekær');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5960,'Marstal');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5965,'Birkholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5970,'Ærøskøbing');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (5985,'Søby Ærø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6000,'Kolding');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6040,'Egtved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6051,'Almind');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6052,'Viuf');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6064,'Jordrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6070,'Christiansfeld');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6091,'Bjert');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6092,'Sønder Stenderup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6093,'Sjølund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6094,'Hejls');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6100,'Haderslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6200,'Aabenraa');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6210,'Barsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6230,'Rødekro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6240,'Løgumkloster');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6261,'Bredebro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6270,'Tønder');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6280,'Højer');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6300,'Gråsten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6310,'Broager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6320,'Egernsund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6330,'Padborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6340,'Kruså');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6360,'Tinglev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6372,'Bylderup-Bov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6392,'Bolderslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6400,'Sønderborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6430,'Nordborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6440,'Augustenborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6470,'Sydals');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6500,'Vojens');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6510,'Gram');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6520,'Toftlund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6534,'Agerskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6535,'Branderup J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6541,'Bevtoft');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6560,'Sommersted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6580,'Vamdrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6600,'Vejen');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6621,'Gesten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6622,'Bække');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6623,'Vorbasse');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6630,'Rødding');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6640,'Lunderskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6650,'Brørup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6660,'Lintrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6670,'Holsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6682,'Hovborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6683,'Føvling');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6690,'Gørding');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6700,'Esbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6701,'Esbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6705,'Esbjerg Ø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6710,'Esbjerg V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6715,'Esbjerg N');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6720,'Fanø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6731,'Tjæreborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6740,'Bramming');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6752,'Glejbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6753,'Agerbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6760,'Ribe');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6771,'Gredstedbro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6780,'Skærbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6792,'Rømø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6800,'Varde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6818,'Årre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6823,'Ansager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6830,'Nørre Nebel');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6840,'Oksbøl');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6851,'Janderup Vestj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6852,'Billum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6853,'Vejers Strand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6854,'Henne');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6855,'Outrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6857,'Blåvand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6862,'Tistrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6870,'Ølgod');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6880,'Tarm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6893,'Hemmet');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6900,'Skjern');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6920,'Videbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6933,'Kibæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6940,'Lem St');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6950,'Ringkøbing');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6960,'Hvide Sande');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6971,'Spjald');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6973,'Ørnhøj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6980,'Tim');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (6990,'Ulfborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7000,'Fredericia');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7007,'Fredericia');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7017,'Taulov Pakkecenter');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7018,'Pakker TLP');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7029,'Fredericia');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7080,'Børkop');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7100,'Vejle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7120,'Vejle Øst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7130,'Juelsminde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7140,'Stouby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7150,'Barrit');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7160,'Tørring');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7171,'Uldum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7173,'Vonge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7182,'Bredsten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7183,'Randbøl');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7184,'Vandel');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7190,'Billund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7200,'Grindsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7250,'Hejnsvig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7260,'Sønder Omme');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7270,'Stakroge');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7280,'Sønder Felding');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7300,'Jelling');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7321,'Gadbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7323,'Give');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7330,'Brande');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7361,'Ejstrupholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7362,'Hampen');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7400,'Herning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7429,'Herning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7430,'Ikast');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7441,'Bording');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7442,'Engesvang');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7451,'Sunds');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7470,'Karup J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7480,'Vildbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7490,'Aulum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7500,'Holstebro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7540,'Haderup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7550,'Sørvad');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7560,'Hjerm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7570,'Vemb');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7600,'Struer');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7620,'Lemvig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7650,'Bøvlingbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7660,'Bækmarksbro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7673,'Harboøre');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7680,'Thyborøn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7700,'Thisted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7730,'Hanstholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7741,'Frøstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7742,'Vesløs');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7752,'Snedsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7755,'Bedsted Thy');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7760,'Hurup Thy');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7770,'Vestervig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7790,'Thyholm');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7800,'Skive');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7830,'Vinderup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7840,'Højslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7850,'Stoholm Jyll');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7860,'Spøttrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7870,'Roslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7884,'Fur');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7900,'Nykøbing M');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7950,'Erslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7960,'Karby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7970,'Redsted M');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7980,'Vils');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7990,'Øster Assels');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7992,'Sydjylland/Fyn USF P');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7993,'Sydjylland/Fyn USF B');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7996,'Fakturaservice');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7997,'Fakturascanning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7998,'Statsservice');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (7999,'Kommunepost');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8000,'Aarhus C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8100,'Aarhus C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8200,'Aarhus N');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8210,'Aarhus V');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8220,'Brabrand');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8229,'Risskov Ø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8230,'Åbyhøj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8240,'Risskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8245,'Risskov Ø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8250,'Egå');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8260,'Viby J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8270,'Højbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8300,'Odder');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8305,'Samsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8310,'Tranbjerg J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8320,'Mårslet');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8330,'Beder');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8340,'Malling');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8350,'Hundslund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8355,'Solbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8361,'Hasselager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8362,'Hørning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8370,'Hadsten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8380,'Trige');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8381,'Tilst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8382,'Hinnerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8400,'Ebeltoft');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8410,'Rønde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8420,'Knebel');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8444,'Balle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8450,'Hammel');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8462,'Harlev J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8464,'Galten');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8471,'Sabro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8472,'Sporup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8500,'Grenaa');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8520,'Lystrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8530,'Hjortshøj');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8541,'Skødstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8543,'Hornslet');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8544,'Mørke');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8550,'Ryomgård');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8560,'Kolind');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8570,'Trustrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8581,'Nimtofte');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8585,'Glesborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8586,'Ørum Djurs');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8592,'Anholt');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8600,'Silkeborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8620,'Kjellerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8632,'Lemming');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8641,'Sorring');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8643,'Ans By');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8653,'Them');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8654,'Bryrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8660,'Skanderborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8670,'Låsby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8680,'Ry');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8700,'Horsens');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8721,'Daugård');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8722,'Hedensted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8723,'Løsning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8732,'Hovedgård');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8740,'Brædstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8751,'Gedved');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8752,'Østbirk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8762,'Flemming');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8763,'Rask Mølle');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8765,'Klovborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8766,'Nørre Snede');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8781,'Stenderup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8783,'Hornsyld');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8789,'Endelave');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8799,'Tunø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8800,'Viborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8830,'Tjele');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8831,'Løgstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8832,'Skals');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8840,'Rødkærsbro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8850,'Bjerringbro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8860,'Ulstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8870,'Langå');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8881,'Thorsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8882,'Fårvang');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8883,'Gjern');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8900,'Randers C');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8920,'Randers NV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8930,'Randers NØ');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8940,'Randers SV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8950,'Ørsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8960,'Randers SØ');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8961,'Allingåbro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8963,'Auning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8970,'Havndal');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8981,'Spentrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8983,'Gjerlev J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (8990,'Fårup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9000,'Aalborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9029,'Aalborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9100,'Aalborg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9200,'Aalborg SV');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9210,'Aalborg SØ');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9220,'Aalborg Øst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9230,'Svenstrup J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9240,'Nibe');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9260,'Gistrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9270,'Klarup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9280,'Storvorde');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9293,'Kongerslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9300,'Sæby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9310,'Vodskov');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9320,'Hjallerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9330,'Dronninglund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9340,'Asaa');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9352,'Dybvad');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9362,'Gandrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9370,'Hals');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9380,'Vestbjerg');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9381,'Sulsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9382,'Tylstrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9400,'Nørresundby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9430,'Vadum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9440,'Aabybro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9460,'Brovst');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9480,'Løkken');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9490,'Pandrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9492,'Blokhus');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9493,'Saltum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9500,'Hobro');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9510,'Arden');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9520,'Skørping');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9530,'Støvring');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9541,'Suldrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9550,'Mariager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9560,'Hadsund');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9574,'Bælum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9575,'Terndrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9600,'Aars');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9610,'Nørager');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9620,'Aalestrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9631,'Gedsted');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9632,'Møldrup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9640,'Farsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9670,'Løgstør');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9681,'Ranum');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9690,'Fjerritslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9700,'Brønderslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9740,'Jerslev J');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9750,'Østervrå');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9760,'Vrå');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9800,'Hjørring');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9830,'Tårs');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9850,'Hirtshals');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9870,'Sindal');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9881,'Bindslev');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9900,'Frederikshavn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9940,'Læsø');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9970,'Strandby');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9981,'Jerup');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9982,'Ålbæk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9990,'Skagen');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9992,'Jylland USF P');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9993,'Jylland USF B');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9996,'Fakturaservice');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9997,'Fakturascanning');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (9998,'Borgerservice');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (2412,'Santa Claus/Julemanden');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3900,'Nuuk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3905,'Nuussuaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3910,'Kangerlussuaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3911,'Sisimiut');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3912,'Maniitsoq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3913,'Tasiilaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3915,'Kulusuk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3919,'Alluitsup Paa');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3920,'Qaqortoq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3921,'Narsaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3922,'Nanortalik');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3923,'Narsarsuaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3924,'Ikerasassuaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3930,'Kangilinnguit');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3932,'Arsuk');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3940,'Paamiut');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3950,'Aasiaat');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3951,'Qasigiannguit');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3952,'Ilulissat');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3953,'Qeqertarsuaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3955,'Kangaatsiaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3961,'Uummannaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3962,'Upernavik');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3964,'Qaarsut');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3970,'Pituffik');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3971,'Qaanaaq');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3972,'Station Nord');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3980,'Ittoqqortoormiit');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3982,'Mestersvig');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3984,'Danmarkshavn');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3985,'Constable Pynt');
INSERT INTO TZipCode(cZipCode,cCityName) VALUES (3992,'Slædepatrulje Sirius');

